<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>CrimsonHue</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../CrimsonHue.Core/CrimsonHue.Core.csproj" /></ItemGroup>
</Project>
